### ISSUE TITLE
Tkinter Threading Issues

### ISSUE THREAD

**Issue by CrCliff** [CrCliff/dota2_overunder#1]
Unable to run install_teams and install_matches without a large cpu load. From my understanding, this somehow locks up the Tkinter GUI and prevents the user from doing anything when the script is installing teams and matches.

Possible solutions:
- Threading out of main thread
- Turning tkinter into class
- Using queue somehow (?) - might be easiest solution 

The following error is produced when I attempt to thread the install_teams_menu method:

>  Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python36-32\dota2_overunder\DotaParser0.1\front_end.py", line 22, in install_teams_menu
    text = e.get()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2676, in get
    return self.tk.call(self._w, 'get')
RuntimeError: main thread is not in main loop

**Comment by CrCliff** [comment]
I was able to utilize the Queue class along with the new threading class to fix the issue. From my understanding, the Queue object is similar to a list, and is able to be passed between threads.
With this fix, the OptionMenu no longer changes when I try to pick an option. This will open another issue.
